version: '3.7'
services:
  database:
    environment: 
      PGDATA: /var/lib/postgresql/data/PGDATA
      POSTGRES_PASSWORD: rpi1234
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    build: ./api
    depends_on:
      - database
    environment:
      MIX_ENV: dev
    env_file:
      - ./api/.env
    ports:
      - '4000:4000'
volumes:
  pgdata: